export const TIRE_SLIDES = [
  {
    img: "https://cdn.poehali.dev/projects/46745fea-3775-44bf-b9bf-65fdd59d5b7d/files/60e35b21-e621-468b-8174-0a89189a9fba.jpg",
    code: "TWR-01",
    label: "Износ внутренней части",
    diagnosis: "Неправильное схождение — увеличенный положительный угол",
    status: "КРИТИЧНО",
    statusColor: "text-red-400",
    accentColor: "border-red-500/50",
    barBg: "bg-red-500",
    wearSide: "inner",
  },
  {
    img: "https://cdn.poehali.dev/projects/46745fea-3775-44bf-b9bf-65fdd59d5b7d/files/466ef476-8230-4387-9691-20a9cd5b3d25.jpg",
    code: "TWR-02",
    label: "Нормальный износ",
    diagnosis: "Геометрия подвески в норме — равномерный контакт с дорогой",
    status: "НОРМА",
    statusColor: "text-green-400",
    accentColor: "border-green-500/50",
    barBg: "bg-green-500",
    wearSide: "none",
  },
  {
    img: "https://cdn.poehali.dev/projects/46745fea-3775-44bf-b9bf-65fdd59d5b7d/files/b52ece48-f92d-46a6-a02a-d638f9bea3fb.jpg",
    code: "TWR-03",
    label: "Износ наружной части",
    diagnosis: "Неправильное схождение — большой отрицательный угол",
    status: "КРИТИЧНО",
    statusColor: "text-red-400",
    accentColor: "border-red-500/50",
    barBg: "bg-red-500",
    wearSide: "outer",
  },
];

export const SERVICES = [
  {
    id: 1,
    icon: "CircleDot",
    title: "Развал-Схождение",
    code: "SRV-01",
    desc: "3D-стенд Technovector. Точность до 0.01°. Все марки авто.",
    price: "от 2 500 ₽",
    tag: "ПОПУЛЯРНОЕ",
    path: "/razvalskhozhdenie",
  },
  {
    id: 2,
    icon: "Settings2",
    title: "Ремонт Ходовой",
    code: "SRV-02",
    desc: "Диагностика, замена амортизаторов, шаровых, сайлентблоков.",
    price: "от 1 500 ₽",
    tag: "",
    path: "/remont-hodovoy",
  },
  {
    id: 3,
    icon: "Thermometer",
    title: "Заправка Кондиционеров",
    code: "SRV-03",
    desc: "Заправка фреоном R134a / R1234yf. Проверка герметичности системы.",
    price: "от 3 000 ₽",
    tag: "СЕЗОН",
    path: "/zapravka-kondicionera",
  },
  {
    id: 4,
    icon: "Wrench",
    title: "Ремонт Рулевых Реек",
    code: "SRV-04",
    desc: "Восстановление без замены. Гарантия и качество всех видов работ и запчастей.",
    price: "от 5 000 ₽",
    tag: "",
    path: "/remont-rulevyh-reek",
  },
];

export const STATS = [
  { value: "15+", label: "лет на рынке" },
  { value: "18 000+", label: "выполненных работ" },
  { value: "98%", label: "довольных клиентов" },
  { value: "★", label: "гарантия и качество работ" },
];